# previous content in application.properties
# we use yml format for readability
#spring.datasource.url=jdbc:postgresql://localhost:5432/users
#spring.datasource.username=
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true

app:
    datasource:
      users:
        url: jdbc:postgresql://localhost:5432/users
        username:
        password:
        configuration:
          maximum-pool-size: 30

      confirmation-token:
        url: jdbc:postgresql://localhost:5432/confirmation_token
        username:
        password:
        configuration:
          maximum-pool-size: 30
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  security:
    user:
      password:
      name:
  mail:
#    TODO set proper config https://support.google.com/mail/answer/7126229?p=BadCredentials&visit_id=637630008844627961-3230683258&rd=2#cantsignin&zippy=%2Ci-cant-sign-in-to-my-email-client
    host: smtp.gmail.com
    port: 587
    username: charles.chenyu1999
    password: Yuchen0420
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/templates/